server:
  port: 8888

spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

kafka:
  bootstrap-servers: localhost:9092 # Адрес Kafka сервера
