spring:
  application:
    name: company-service
  cloud:
    config:
      url: ${CONFIG_SERVER_URL}
  datasource:
    flyway:
      enabled: true
      locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
