spring:
  application:
    name: user-service
  cloud:
    config:
      url: ${CONFIG_SERVER_URL}
  datasource:
    flyway:
      enabled: true
      locations: classpath:db/migration
#  kafka:
#    bootstrap-servers: localhost:9092  # Адрес Kafka сервера

#kafka:
#  listener:
#    topic: company-deletion-topic  # Тема для получения сообщений об удалении компании
#  template:
#    default-topic: company-physical-deletion-topic # Тема для отправки сообщения обратно в Company Service после сброса company_id у пользователей

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
