--CREATE SCHEMA IF NOT EXISTS user_schema;

CREATE TABLE IF NOT EXISTS "user"
(
    id bigint generated by default as identity
        constraint user_pkey
        primary key,
    name varchar(200) not null,
    password varchar(256) not null,
    login varchar(256) not null,
    email varchar(256) not null,
    enabled bool,
    company_id bigint
);