CREATE TABLE IF NOT EXISTS company
(
    id bigint generated by default as identity
        constraint company_pkey
        primary key,
    name VARCHAR(200) NOT NULL,
    ogrn VARCHAR(13) NOT NULL,
    description TEXT,
    director_id BIGINT
);