# company-service.yml
server:
  port: 8089

custom:
  property:
    description: Hello! It's company-service prod

spring:
  datasource:
    url:  jdbc:postgresql://host.docker.internal:5433/microservices?currentSchema=company-schema