# company-service.yml
server:
  port: 8089

custom:
  property:
    description: Hello! It's company-service prod

spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5433/microservices?currentSchema=company-schema
    driver-class-name: org.postgresql.Driver
