# user-service.yml
server:
  port: 8090

custom:
  property:
    description: Hello! It's user-service prod

spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5433/microservices?currentSchema=user-schema
    driver-class-name: org.postgresql.Driver
