# user-service.yml
server:
  port: 8090

custom:
  property:
    description: Hello! It's user-service prod

spring:
  datasource:
    url:  jdbc:postgresql://host.docker.internal:5433/microservices?currentSchema=user-schema
